export type WorkflowState =
  | "open"
  | "classified"
  | "matched"
  | "awaiting_approval"
  | "approved_ready_to_send"
  | "sent"
  | "resolved"
  | "escalated";

export function deriveWorkflowState(params: {
  threadStatus: string;
  hasClassification: boolean;
  hasMatchedLoad: boolean;
  draftStatus?: string | null;
}): WorkflowState {
  const { threadStatus, draftStatus, hasClassification, hasMatchedLoad } = params;
  if (threadStatus === "resolved")  return "resolved";
  if (threadStatus === "escalated") return "escalated";
  if (threadStatus === "sent")      return "sent";
  if (draftStatus === "approved")   return "approved_ready_to_send";
  if (draftStatus === "pending" || draftStatus === "edited") return "awaiting_approval";
  if (hasMatchedLoad)               return "matched";
  if (hasClassification)            return "classified";
  return "open";
}

export const WORKFLOW_LABEL: Record<WorkflowState, string> = {
  open:                   "Open — Needs Classification",
  classified:             "Classified — Generate Draft",
  matched:                "Load Matched — Generate Draft",
  awaiting_approval:      "Awaiting Approval",
  approved_ready_to_send: "Approved — Ready to Send",
  sent:                   "Sent Manually — Resolve?",
  resolved:               "Resolved",
  escalated:              "Escalated",
};

export const ACTION_LABELS: Record<string, string> = {
  email_received:         "Email received",
  classification_created: "Classified by Clyde AI",
  thread_classified:      "Thread classified",
  draft_generated:        "Draft generated by Clyde AI",
  draft_approved:         "Draft approved",
  draft_rejected:         "Draft rejected",
  draft_edited:           "Draft edited",
  marked_sent_manually:   "Marked as sent manually",
  thread_resolved:        "Thread resolved",
  thread_escalated:       "Thread escalated",
  load_matched:           "Load matched",
  status_updated:         "Status updated",
  document_requested:     "Document requested",
};

export function actionLabel(action: string): string {
  return ACTION_LABELS[action] ?? action.replace(/_/g, " ");
}
